###########################################################################
# %seller% - returns the seller's name                                    #
# %item% - returns the item's name                                        #
# %displayname% - returns the item's display name                         #
# %amount% - returns the item's amount                                    #
# %price% - returns the item's price                                      #
# %auction_id% - returns the auction's ID                                 #
# %buyer% - returns the buyer's name (if null, it will return "N/A")      #
###########################################################################

# This config option needs the channel's ID,
channel: ""

sell-embed:
  enabled: true
  author: "%seller% is selling %item% for $%price%"
  color: "#4287f5"
  title: "Auction Information"
  footer: "Auction ID: %auction_id%"
  fields:
    Seller:
      name: "Seller"
      value: "%seller%"
      inline: true
    blank:
      name: ""
      value: ""
      inline: true
    Item:
      name: "Item"
      value: "%item%"
      inline: true
    Amount:
      name: "Amount"
      value: "%amount%"
      inline: true
    blank1:
      name: ""
      value: ""
      inline: true
    Price:
      name: "Price"
      value: "%price%"
      inline: true
buy-embed:
  enabled: true
  author: "%buyer% bought %item% for $%price%"
  color: "#48f542"
  title: "Auction Information"
  footer: "Auction ID: %auction_id%"
  fields:
    Seller:
      name: "Seller"
      value: "%seller%"
      inline: true
    Buyer:
      name: "Buyer"
      value: "%buyer%"
      inline: true
    Item:
      name: "Item"
      value: "%item%"
      inline: true
    Amount:
      name: "Amount"
      value: "%amount%"
      inline: true
    blank1:
      name: ""
      value: ""
      inline: true
    Price:
      name: "Price"
      value: "%price%"
      inline: true
remove-embed:
  enabled: true
  author: "%item% was removed from the Auction!"
  color: "#bf2a2a"
  title: "Auction Information"
  footer: "Auction ID: %auction_id%"
  fields:
    Seller:
      name: "Seller"
      value: "%seller%"
      inline: true
    blank:
      name: ""
      value: ""
      inline: true
    Item:
      name: "Item"
      value: "%item%"
      inline: true
    Amount:
      name: "Amount"
      value: "%amount%"
      inline: true
    blank1:
      name: ""
      value: ""
      inline: true
    Price:
      name: "Price"
      value: "%price%"
      inline: true
