name: PlayerAuctionsDiscord
version: ${project.version}
main: me.faun.playerauctionsdiscord.PlayerAuctionsDiscord
api-version: 1.17
depend: [ DiscordSRV, PlayerAuctions ]
commands:
  PlayerAuctionsDiscord:
    usage: "Usage /playerauctionsdiscord reload"
    aliases:
      - "pad"
    description: "Main command of PlayerAuctionsDiscord"
